services:
    app:
        build:
            context: ./docker/php
        user: "1000:1000"
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - db
        networks:
            - laravel-network

    web:
        build:
            context: ./docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    db:
        image: mysql:8.0
        platform: linux/amd64
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-network

    node:
        image: node:18-alpine
        working_dir: /app
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        command: sh -c "npm ci && npm run dev"
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    mysql-data:
